platform :ios, '15.0'
use_frameworks!

def capacitor_pods
  # Core
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  
  # Standard Plugins (Manually Linked)
  pod 'CapacitorDevice', :path => '../../node_modules/@capacitor/device'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  
  # Community Plugins
  pod 'CapacitorCommunityStripeTerminal', :path => '../../node_modules/@capacitor-community/stripe-terminal'
end

target 'App' do
  capacitor_pods
  pod 'OneSignal', '>= 3.0', '< 6.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
